TMS/Models/db/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TMS.Models
{
    public class Team
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }

        // Foriegn Key
        public int OwnerId { get; set; }
        [ForeignKey("OwnerId")]
        public virtual UserDetail UserDetails { get; set; }
    }
}

TMS/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using TMS.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace TMS.Controllers
{
    public class TeamController : Controller
    {
        ApplicationUser appUser;
        RoleNames roles = new RoleNames();
        string curUserRole;
        UserRoleProvider urp = new UserRoleProvider();
        private APICall api = new APICall();
        private General general = new General();
        
        string APIURL = "TeamData/";
        string APIURL1 = "UserDetailsData/";
        string APIURL2 = "TeamPlayerData/";

        public TeamController()
        {
            appUser = api.getCurrentUser();
            if (!String.IsNullOrEmpty(appUser.Id))
            {
                curUserRole = urp.getRoleFromId(appUser.Roles.FirstOrDefault().RoleId);
            }
        }

        // GET: Team/
        public ActionResult Index(string Search)
        {
            api.GetApplicationCookie();

            string url1 = APIURL1 + "GetUserDetails/" + appUser.Id;
            List<TeamDto> teams = new List<TeamDto>();
            UserDetailDto userDetails = new UserDetailDto();

            HttpResponseMessage response1 = api.Get(url1);

            if (response1.StatusCode == HttpStatusCode.OK)
                userDetails = response1.Content.ReadAsAsync<UserDetailDto>().Result;

            string url = APIURL + "ListTeamsByOwner/" + userDetails.Id;
            HttpResponseMessage response = api.Get(url);
            if (response.StatusCode == HttpStatusCode.OK)
                teams = response.Content.ReadAsAsync<IEnumerable<TeamDto>>().Result.ToList();

            if (!String.IsNullOrEmpty(Search))
                teams = teams.Where(x =>
                    general.getLowerStringForSearch(x.Name).Contains(general.getLowerStringForSearch(Search)) ||
                    general.getLowerStringForSearch(x.Country).Contains(general.getLowerStringForSearch(Search))
                ).ToList();

            ViewData["title"] = "Team List";
            ViewData["search"] = Search;
            //ViewData["user"] = userDetails;
            //ViewData["role"] = curUserRole;

            return View(teams);
        }

        // GET: Team/Details/5
        public ActionResult Details(int id)
        {
            api.GetApplicationCookie();
            TeamDto selectedTeam = new TeamDto();
            string url = APIURL + "FindTeam/" + id;
            string url1 = APIURL2 + "ListTeamPlayers/" + id;

            HttpResponseMessage response = api.Get(url);
            if (response.StatusCode == HttpStatusCode.OK)
                selectedTeam = response.Content.ReadAsAsync<TeamDto>().Result;

            HttpResponseMessage response1 = api.Get(url1);
            if (response1.StatusCode == HttpStatusCode.OK)
                selectedTeam.ListTeamPlayers = response1.Content.ReadAsAsync<IEnumerable<UserDetailDto>>().Result.ToList();

            ViewData["title"] = "Team Details";
            return View(selectedTeam);
        }
        
        // GET: Team/Create
        public ActionResult Create()
        {
            ViewData["title"] = "Create Team";
            return View();
        }   


        // POST: Team/Create
        [HttpPost]
        public ActionResult Create(TeamDto teamDto)
        {
            try
            {
                api.GetApplicationCookie();

                string url1 = APIURL1 + "GetUserDetails/" + appUser.Id;

                UserDetailDto userDetails = new UserDetailDto();
                HttpResponseMessage response1 = api.Get(url1);

                if (response1.StatusCode == HttpStatusCode.OK)
                    userDetails = response1.Content.ReadAsAsync<UserDetailDto>().Result;

                string url = APIURL + "AddTeam";
                Team team = new Team()
                {
                    Name = teamDto.Name,
                    Country = teamDto.Country,
                    OwnerId = userDetails.Id
                };

                HttpResponseMessage response = api.Post(url, team);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(String.Concat("/"));
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Team/Edit/5
        public ActionResult Edit(int id)
        {
            api.GetApplicationCookie();

            string url = APIURL + "FindTeam/" + id;
            HttpResponseMessage response = api.Get(url);
            TeamDto selectedTeam = new TeamDto();

            if (response.StatusCode == HttpStatusCode.OK)
                selectedTeam = response.Content.ReadAsAsync<TeamDto>().Result;

            ViewData["title"] = "Edit Team";

            return View(selectedTeam);
        }



        // POST: Team/Update/5
        [HttpPost]
        public ActionResult Update(int id, Team teamDto)
        {
            try
            {
                api.GetApplicationCookie();

                Team team = new Team()
                {
                    Name = teamDto.Name,
                    Id = teamDto.Id,
                    Country = teamDto.Country,
                    OwnerId = teamDto.OwnerId
                };

                string url = APIURL + "UpdateTeam/" + id;

                HttpResponseMessage response = api.Post(url, team);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(String.Concat("Details/", id));
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Team/Delete/5
        public ActionResult DeleteConfirm(int id)
        {
            api.GetApplicationCookie();

            string url = APIURL + "FindTeam/" + id;
            HttpResponseMessage response = api.Get(url);
            TeamDto selectedTeam = new TeamDto();

            if (response.StatusCode == HttpStatusCode.OK)
                selectedTeam = response.Content.ReadAsAsync<TeamDto>().Result;

            ViewData["title"] = "Edit Team";

            return View(selectedTeam);
        }

        // POST: Team/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                api.GetApplicationCookie();

                string url = APIURL + "DeleteTeam/" + id;
                Object obj = new Object();

                HttpResponseMessage response = api.Post(url, obj);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("/");
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Error()
        {

            return View();
        }
    }
}

TMS/Controllers/TeamPlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using TMS.Models;

namespace TMS.Controllers
{
    public class TeamPlayerController : Controller
    {
        ApplicationUser appUser;
        RoleNames roles = new RoleNames();
        string curUserRole;
        UserRoleProvider urp = new UserRoleProvider();
        private APICall api = new APICall();
        private General general = new General();

        string APIURL = "TeamPlayerData/";
        string APIURL1 = "UserDetailsData/";

        public TeamPlayerController()
        {
            appUser = api.getCurrentUser();
            if (!String.IsNullOrEmpty(appUser.Id))
            {
                curUserRole = urp.getRoleFromId(appUser.Roles.FirstOrDefault().RoleId);
            }
        }

        // GET: TeamPlayer
        public ActionResult Index()
        {
            return View();
        }

        // GET: TeamPlayer/ReleasePlayer/5
        public ActionResult AddTeamPlayerToTeam(int id)
        {
            TeamPlayerDto teamPlayerDto = new TeamPlayerDto();
            teamPlayerDto.TeamId = id;

            string url = APIURL + "ListPlayers";

            HttpResponseMessage response = api.Get(url);

            if (response.StatusCode == HttpStatusCode.OK)
                teamPlayerDto.LstPlayers = response.Content.ReadAsAsync<IEnumerable<UserDetailDto>>().Result.ToList();

            ViewData["title"] = "Team Details";
            return View(teamPlayerDto);
        }

        [HttpPost]
        public ActionResult AddTeamPlayerToTeam(TeamPlayerDto teamPlayerDto)
        {
            TeamPlayerAssociation teamPLayer = new TeamPlayerAssociation()
            {
                PlayerId = teamPlayerDto.PlayerId,
                //JoinedDate = DateTime.Now,
                //JoinedPrice = teamPlayerDto.JoinedPrice,
                TeamId = teamPlayerDto.TeamId
            };

            string url = APIURL + "AddTeamPlayer/";
            HttpResponseMessage response = api.Post(url, teamPLayer);

            ViewData["title"] = "Team Details";

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction(String.Concat("Details/", teamPlayerDto.TeamId), "Team");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }


        // GET: TeamPlayer/ReleasePlayer/5
        public ActionResult ReleasePlayer(int id)
        {
            string url = APIURL + "FineTeamPlayer/" + id;
            HttpResponseMessage response = api.Get(url);

            TeamPlayerDto selectedTeamPlayer = new TeamPlayerDto();

            if (response.StatusCode == HttpStatusCode.OK)
                selectedTeamPlayer = response.Content.ReadAsAsync<TeamPlayerDto>().Result;

            ViewData["title"] = "Team Details";

            return View(selectedTeamPlayer);
        }

        // POST: TeamPlayer/ReleasePlayer/5
        [HttpPost]
        public ActionResult ReleaseTeamPlayer(int id, int teamId)
        {
            string url = APIURL + "ReleaseTeamPlayer/" + id;
            HttpResponseMessage response = api.Get(url);

            ViewData["title"] = "Team Details";

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction(String.Concat("Details/", teamId), "Team");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
    }
}

TMS/Views/Team/Create.cshtml
@model TMS.Models.TeamDto
@{
    ViewBag.Title = "New";
}

<h2>Add Team</h2>
<div id="containershow">
    <nav class="my-2">
        <a class="btn btn-secondary navlink" href="/Team">Back To Teams</a>
    </nav>
    <form method="POST" action="/Team/Create">
        <div class="inputrow my-2">
            <label for="Name">Name:</label>
            <input type="text" id="Name" name="Name" />
        </div>
        <div class="inputrow my-2">
            <label for="Country">Country:</label>
            <input type="text" id="Country" name="Country" />
        </div>
        <div class="inputrow my-2">
            <input class="btn btn-primary" type="submit" value="Create Team" />
        </div>
    </form>
</div>

TMS/Views/Team/DeleteConfirm.cshtml
@model TMS.Models.TeamDto

@{
    ViewBag.Title = "DeleteConfirm";
}

<h2>Are you sure you want to delete this Team?</h2>
<a href="/Team">Cancel</a>
<h2>@Model.Name</h2>
<form action="/Team/Delete/@Model.Id" method="POST">
    <input type="submit" class="btn btn-primary" value="Confirm Delete" />
</form>

TMS/Views/Team/Details.cshtml
@model TMS.Models.TeamDto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<hr />
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

    </dl>
</div>

<nav class="my-2">
    <a class="btn btn-primary navlink" href="/TeamPlayer/AddTeamPlayerToTeam/@Model.Id">Add Team Player</a>
</nav>

@*<div class="row">
    <div class="col-12">
        <form asp-controller="Team" asp-action="Index">
            <p>
                Search: <input type="text" name="Search" value="@ViewData["search"]" />
                <input type="submit" class="btn btn-primary" value="Search" />
            </p>
        </form>
    </div>
</div>*@

<div class="row">
    <div class="col-12">
        <table border="1">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Team Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.ListTeamPlayers.Count() == 0)
                {
                    <tr class="text-center">
                        <td colspan="5">No Data Found</td>
                    </tr>
                }
                @{ int i = 1; }
                @foreach (var item in Model.ListTeamPlayers)
                {
                    <tr>
                        <td>@i</td>
                        <td>@item.FName @item.LName</td>
                        <td>
                            @*@Html.ActionLink("View", "Details", new { id = @item.Id }, new { @class = "btn btn-primary" })*@
                            @*@Html.ActionLink("Edit", "Edit", new { id = @item.Id }, new { @class = "btn btn-warning" })*@
                            @Html.ActionLink("Release Player", "ReleasePlayer", "TeamPlayer", new { id = @item.Id }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>

                    i++;
                }
            </tbody>
        </table>
    </div>
</div>

<style>
    nav {
        padding-bottom: 1em;
    }

    table {
        width: 100%;
    }

    thead, tbody, tfoot, tr, td, th {
        border-width: 1px;
        padding: 0.25em;
    }
</style>

TMS/Views/Team/Edit.cshtml
@model TMS.Models.TeamDto
@{
    ViewBag.Title = "Edit";
}

<h2>Edit Team</h2>
<div id="containershow">
    <nav class="my-2">
        <a class="btn btn-secondary navlink" href="/Team">Back To Teams</a>
    </nav>
    <form action="/Team/Update/@Model.Id" method="POST">
        <div style="display:none;">
            <input type="text" name="TeamId" value="@Model.Id" />
            <input type="text" name="OwnerId" value="@Model.OwnerId" />
        </div>
        <div class="inputrow my-2">
            <label for="Name">Name:</label>
            <input type="text" id="Name" name="Name" value="@Model.Name" />
        </div>
        <div class="inputrow my-2">
            <label for="Country">Country:</label>
            <input type="text" id="Country" name="Country" value="@Model.Country" />
        </div>
        <div class="inputrow my-2">
            <input class="btn btn-primary" type="submit" value="Update Team" />
        </div>
    </form>
</div>

TMS/Views/Team/Index.cshtml
@model IEnumerable<TMS.Models.TeamDto>
@{
    ViewBag.Title = "List";
}

<h2>@ViewData["title"]</h2>

<nav class="my-2">
    <a class="btn btn-primary navlink" href="/Team/Create">Add Team</a>
</nav>

<div class="row">
    <div class="col-12">
        <form asp-controller="Team" asp-action="Index">
            <p>
                Search: <input type="text" name="Search" value="@ViewData["search"]" />
                <input type="submit" class="btn btn-primary" value="Search" />
            </p>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <table border="1">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Team Name</th>
                    <th>Country</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count() == 0)
                {
                    <tr class="text-center">
                        <td colspan="5">No Data Found</td>
                    </tr>
                }
                @{ int i = 1; }
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@i</td>
                        <td>@item.Name</td>
                        <td>@item.Country</td>
                        <td>
                            @Html.ActionLink("View", "Details", new { id = @item.Id }, new { @class = "btn btn-primary" })
                            @Html.ActionLink("Edit", "Edit", new { id = @item.Id }, new { @class = "btn btn-warning" })
                            @Html.ActionLink("Delete", "DeleteConfirm", new { id = @item.Id }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>

                    i++;
                }
            </tbody>
        </table>
    </div>
</div>

<style>
    nav {
        padding-bottom: 1em;
    }
    table {
        width: 100%;
    }

    thead, tbody, tfoot, tr, td, th {
        border-width: 1px;
        padding: 0.25em;
    }
</style>