TMS/Models/db/Venue.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TMS.Models
{
    public class Venue
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal BasePrice { get; set; }
        public string Location { get; set; }
        public string Country { get; set; }
    }
}

TMS/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http.Results;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using TMS.Models;

namespace TMS.Controllers
{
    public class MatchController : Controller
    {
        string APIURL = "MatchData/";
        string APIURL1 = "TeamData/";
        string APIURL2 = "TournamentVenuesData/";
        private APICall api = new APICall();
        private General general = new General();

        private void GetApplicationCookie()
        {
            HttpClient client = api.getClient();
            string token = "";
            //HTTP client is set up to be reused, otherwise it will exhaust server resources.
            //This is a bit dangerous because a previously authenticated cookie could be cached for
            //a follow-up request from someone else. Reset cookies in HTTP client before grabbing a new one.
            client.DefaultRequestHeaders.Remove("Cookie");
            if (!User.Identity.IsAuthenticated) return;

            HttpCookie cookie = System.Web.HttpContext.Current.Request.Cookies.Get(".AspNet.ApplicationCookie");
            if (cookie != null) token = cookie.Value;

            //collect token as it is submitted to the controller
            //use it to pass along to the WebAPI.
            Debug.WriteLine("Token Submitted is : " + token);
            if (token != "") client.DefaultRequestHeaders.Add("Cookie", ".AspNet.ApplicationCookie=" + token);

            return;
        }

        // GET: Match
        public ActionResult Index(string Search)
        {
            string url = APIURL + "Listmatches";
            HttpResponseMessage response = api.Get(url);
            List<MatchDto> matches = new List<MatchDto>();

            if (response.StatusCode == HttpStatusCode.OK)
                matches = response.Content.ReadAsAsync<IEnumerable<MatchDto>>().Result.ToList();

            if (!String.IsNullOrEmpty(Search))
                matches = matches.Where(x =>
                    general.getLowerStringForSearch(String.Concat(x.Team1, " vs ", x.Team2))
                    .Contains(general.getLowerStringForSearch(Search)) ||
                    general.getLowerStringForSearch(x.TournamentVenue.VenueDetail.Name)
                    .Contains(general.getLowerStringForSearch(Search))
                ).ToList();

            ViewData["search"] = Search;

            return View(matches);
        }

        // GET: Match/Details/5
        public ActionResult Details(int id)
        {
            string url = APIURL + "FindMatch/" + id;

            HttpResponseMessage response = api.Get(url);
            MatchDto selectedMatch = new MatchDto();

            if (response.StatusCode == HttpStatusCode.OK)
                selectedMatch = response.Content.ReadAsAsync<MatchDto>().Result;

            ViewData["title"] = "Match Details";
            return View(selectedMatch);
        }

        public ActionResult Error()
        {

            return View();
        }

        // GET: Match/Create
        public ActionResult Create()
        {
            MatchDto matchDto = new MatchDto();

            string url = APIURL1 + "ListTeams";
            string url1 = APIURL2 + "ListTournamentVenues";

            HttpResponseMessage response = api.Get(url);

            if (response.StatusCode == HttpStatusCode.OK)
                matchDto.Teams = response.Content.ReadAsAsync<IEnumerable<TeamDto>>().Result.ToList();

            HttpResponseMessage response1 = api.Get(url1);

            if (response1.StatusCode == HttpStatusCode.OK)
                matchDto.TournamentVenues = response1.Content.ReadAsAsync<IEnumerable<TournamentVenueAssociationDto>>().Result.ToList();

            ViewData["title"] = "Create Match";
            return View(matchDto);
        }

        [HttpPost]
        public ActionResult Create(MatchDto matchDto)
        {
            try
            {
                string url = APIURL + "AddMatch";

                Match match = new Match()
                {
                    DateTime = matchDto.DateTime,
                    Team1Id = matchDto.Team1Id,
                    Team2Id = matchDto.Team2Id,
                    TournamentVenueId = matchDto.TournamentVenueId
                };

                HttpResponseMessage response = api.Post(url, match);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("/");
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            catch
            {
                return View();
            }

        }
    
        // GET: Match/Edit/5
        public ActionResult Edit(int id)
        {
            MatchDto selectedMatch = new MatchDto();
            string url = APIURL + "FindMatch/" + id;
            string url1 = APIURL1 + "ListTeams";
            string url2 = APIURL2 + "ListTournamentVenues";

            HttpResponseMessage response = api.Get(url);
            if (response.StatusCode == HttpStatusCode.OK)
                selectedMatch = response.Content.ReadAsAsync<MatchDto>().Result;

            HttpResponseMessage response1 = api.Get(url1);
            if (response1.StatusCode == HttpStatusCode.OK)
                selectedMatch.Teams = response1.Content.ReadAsAsync<IEnumerable<TeamDto>>().Result.ToList();

            HttpResponseMessage response2 = api.Get(url2);
            if (response2.StatusCode == HttpStatusCode.OK)
                selectedMatch.TournamentVenues = response2.Content.ReadAsAsync<IEnumerable<TournamentVenueAssociationDto>>().Result.ToList();

            ViewData["title"] = "Match Update";
            return View(selectedMatch);
        }

        // POST: Match/Update/5
        [HttpPost]
        public ActionResult Update(int id, MatchDto matchDto)
        {
            try
            {
                string url = APIURL + "UpdateMatch/" + id;
                Match match = new Match()
                {
                    Id= id,
                    DateTime = matchDto.DateTime,
                    Team1Id = matchDto.Team1Id,
                    Team2Id = matchDto.Team2Id,
                    TournamentVenueId = matchDto.TournamentVenueId
                };

                HttpResponseMessage response = api.Post(url, match);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("/");
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Match/Delete/5
        public ActionResult DeleteConfirm(int id)
        {
            string url = APIURL + "FindMatch/" + id;

            HttpResponseMessage response = api.Get(url);
            MatchDto selectedMatch = new MatchDto();

            if (response.StatusCode == HttpStatusCode.OK)
                selectedMatch = response.Content.ReadAsAsync<MatchDto>().Result;

            ViewData["title"] = "Match Update";
            return View(selectedMatch);
        }

        // POST: Match/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try 
            { 
                string url = APIURL + "DeleteMatch/" + id;
                Object obj = new Object();

                HttpResponseMessage response = api.Post(url, obj);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("/");
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

TMS/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using TMS.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace TMS.Controllers
{
    public class TeamController : Controller
    {
        ApplicationUser appUser;
        RoleNames roles = new RoleNames();
        string curUserRole;
        UserRoleProvider urp = new UserRoleProvider();
        private APICall api = new APICall();
        private General general = new General();
        
        string APIURL = "TeamData/";
        string APIURL1 = "UserDetailsData/";
        string APIURL2 = "TeamPlayerData/";

        public TeamController()
        {
            appUser = api.getCurrentUser();
            if (!String.IsNullOrEmpty(appUser.Id))
            {
                curUserRole = urp.getRoleFromId(appUser.Roles.FirstOrDefault().RoleId);
            }
        }

        // GET: Team/
        public ActionResult Index(string Search)
        {
            api.GetApplicationCookie();

            string url1 = APIURL1 + "GetUserDetails/" + appUser.Id;
            List<TeamDto> teams = new List<TeamDto>();
            UserDetailDto userDetails = new UserDetailDto();

            HttpResponseMessage response1 = api.Get(url1);

            if (response1.StatusCode == HttpStatusCode.OK)
                userDetails = response1.Content.ReadAsAsync<UserDetailDto>().Result;

            string url = APIURL + "ListTeamsByOwner/" + userDetails.Id;
            HttpResponseMessage response = api.Get(url);
            if (response.StatusCode == HttpStatusCode.OK)
                teams = response.Content.ReadAsAsync<IEnumerable<TeamDto>>().Result.ToList();

            if (!String.IsNullOrEmpty(Search))
                teams = teams.Where(x =>
                    general.getLowerStringForSearch(x.Name).Contains(general.getLowerStringForSearch(Search)) ||
                    general.getLowerStringForSearch(x.Country).Contains(general.getLowerStringForSearch(Search))
                ).ToList();

            ViewData["title"] = "Team List";
            ViewData["search"] = Search;
            //ViewData["user"] = userDetails;
            //ViewData["role"] = curUserRole;

            return View(teams);
        }

        // GET: Team/Details/5
        public ActionResult Details(int id)
        {
            api.GetApplicationCookie();
            TeamDto selectedTeam = new TeamDto();
            string url = APIURL + "FindTeam/" + id;
            string url1 = APIURL2 + "ListTeamPlayers/" + id;

            HttpResponseMessage response = api.Get(url);
            if (response.StatusCode == HttpStatusCode.OK)
                selectedTeam = response.Content.ReadAsAsync<TeamDto>().Result;

            HttpResponseMessage response1 = api.Get(url1);
            if (response1.StatusCode == HttpStatusCode.OK)
                selectedTeam.ListTeamPlayers = response1.Content.ReadAsAsync<IEnumerable<UserDetailDto>>().Result.ToList();

            ViewData["title"] = "Team Details";
            return View(selectedTeam);
        }
        
        // GET: Team/Create
        public ActionResult Create()
        {
            ViewData["title"] = "Create Team";
            return View();
        }   


        // POST: Team/Create
        [HttpPost]
        public ActionResult Create(TeamDto teamDto)
        {
            try
            {
                api.GetApplicationCookie();

                string url1 = APIURL1 + "GetUserDetails/" + appUser.Id;

                UserDetailDto userDetails = new UserDetailDto();
                HttpResponseMessage response1 = api.Get(url1);

                if (response1.StatusCode == HttpStatusCode.OK)
                    userDetails = response1.Content.ReadAsAsync<UserDetailDto>().Result;

                string url = APIURL + "AddTeam";
                Team team = new Team()
                {
                    Name = teamDto.Name,
                    Country = teamDto.Country,
                    OwnerId = userDetails.Id
                };

                HttpResponseMessage response = api.Post(url, team);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(String.Concat("/"));
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Team/Edit/5
        public ActionResult Edit(int id)
        {
            api.GetApplicationCookie();

            string url = APIURL + "FindTeam/" + id;
            HttpResponseMessage response = api.Get(url);
            TeamDto selectedTeam = new TeamDto();

            if (response.StatusCode == HttpStatusCode.OK)
                selectedTeam = response.Content.ReadAsAsync<TeamDto>().Result;

            ViewData["title"] = "Edit Team";

            return View(selectedTeam);
        }



        // POST: Team/Update/5
        [HttpPost]
        public ActionResult Update(int id, Team teamDto)
        {
            try
            {
                api.GetApplicationCookie();

                Team team = new Team()
                {
                    Name = teamDto.Name,
                    Id = teamDto.Id,
                    Country = teamDto.Country,
                    OwnerId = teamDto.OwnerId
                };

                string url = APIURL + "UpdateTeam/" + id;

                HttpResponseMessage response = api.Post(url, team);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(String.Concat("Details/", id));
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Team/Delete/5
        public ActionResult DeleteConfirm(int id)
        {
            api.GetApplicationCookie();

            string url = APIURL + "FindTeam/" + id;
            HttpResponseMessage response = api.Get(url);
            TeamDto selectedTeam = new TeamDto();

            if (response.StatusCode == HttpStatusCode.OK)
                selectedTeam = response.Content.ReadAsAsync<TeamDto>().Result;

            ViewData["title"] = "Edit Team";

            return View(selectedTeam);
        }

        // POST: Team/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                api.GetApplicationCookie();

                string url = APIURL + "DeleteTeam/" + id;
                Object obj = new Object();

                HttpResponseMessage response = api.Post(url, obj);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("/");
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Error()
        {

            return View();
        }
    }
}

TMS/Views/Venue/Create.cshtml
@model IEnumerable<TMS.Models.VenueDto>
@{
    ViewBag.Title = "New";
}

<h2>Create Venue</h2>
<div id="containershow">
    <nav class="my-2">
        <a class="btn btn-secondary navlink" href="/Venue">Back To Venues</a>
    </nav>
    <form method="POST" action="/Venue/Create">
        <div class="inputrow my-2">
            <label for="Name">Name:</label>
            <input type="text" id="Name" name="Name" />
        </div>
        <div class="inputrow my-2">
            <label for="Country">Country:</label>
            <input type="text" id="Country" name="Country" />
        </div>
        <div class="inputrow my-2">
            <label for="Location">Location:</label>
            <input type="text" id="Location" name="Location" />
        </div>
        <div class="inputrow my-2">
            <label for="BasePrice">Base Price:</label>
            <input type="number" min="0" step="0.01" value="0" id="BasePrice" name="BasePrice" />
        </div>
        <div class="inputrow my-2">
            <input class="btn btn-primary" type="submit" value="Create Venue" />
        </div>
    </form>
</div>

TMS/Views/Venue/DeleteConfirm.cshtml
@model TMS.Models.AgentVenueAssociationDto

@{
    ViewBag.Title = "DeleteConfirm";
}

<h2>Are you sure you want to delete this Venue?</h2>
<a href="/Venue">Cancel</a>
<h2>@Model.VenueDetail.Name</h2>
<form action="/Venue/Delete/@Model.Id" method="POST">
    <div style="display: none;">
        <input type="text" name="Id" value="@Model.Id" />
        <input type="text" name="AgentId" value="@Model.AgentId" />
        <input type="text" name="VenueId" value="@Model.VenueId" />
    </div>
    <input type="submit" class="btn btn-primary" value="Confirm Delete" />
</form>

TMS/Views/Venue/Details.cshtml
@model TMS.Models.AgentVenueAssociationDto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Venue</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VenueDetail.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VenueDetail.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VenueDetail.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VenueDetail.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VenueDetail.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VenueDetail.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VenueDetail.BasePrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VenueDetail.BasePrice)
        </dd>

        <dt>
            Agent Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgentDetail.FName) @Html.DisplayFor(model => model.AgentDetail.LName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VenueDetail.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TMS/Views/Venue/Edit.cshtml
@model TMS.Models.VenueDto
@{
    ViewBag.Title = "Edit";
}

<h2>Edit Venue</h2>
<div id="containershow">
    <nav class="my-2">
        <a class="btn btn-secondary navlink" href="/Venue">Back To Venues</a>
    </nav>
    <form action="/Venue/Update/@Model.Id" method="POST">
        <div style="display:none;">
            <input type="text" name="VenueId" value="@Model.Id" />
        </div>
        <div class="inputrow my-2">
            <label for="Name">Name:</label>
            <input type="text" id="Name" name="Name" value="@Model.Name" />
        </div>
        <div class="inputrow my-2">
            <label for="Country">Country:</label>
            <input type="text" id="Country" name="Country" value="@Model.Country" />
        </div>
        <div class="inputrow my-2">
            <label for="Location">Location:</label>
            <input type="text" id="Location" name="Location" value="@Model.Location" />
        </div>
        <div class="inputrow my-2">
            <label for="BasePrice">Base Price:</label>
            <input type="number" min="0" step="0.01" id="BasePrice" name="BasePrice" value="@Model.BasePrice" />
        </div>
        <div>
            <input type="submit" class="btn btn-primary" value="Update Venue" />
        </div>
    </form>
</div>

TMS/Views/Venue/Index.cshtml
@model IEnumerable<TMS.Models.AgentVenueAssociationDto>
@{
    ViewBag.Title = "List";
}

@*<h2>List</h2>
<a href="/Venue/Create">New Venue</a>

@foreach (var Venue in Model)
{
    <h2>@Venue.Name</h2>
    <div>Base Price: @Venue.BasePrice</div>
    <div>Location: @Venue.Location</div>
    <div>Country: @Venue.Country</div>

    <div><a href="/Venue/Edit/@Venue.Id">Edit</a></div>
    <div><a href="/Venue/DeleteConfirm/@Venue.Id">Delete</a></div>


    // <a href="@Url.Action("ListMatchesForVenue", "Match", new { venueId = Venue.VenueId })">View Matches</a>
}*@

<nav class="my-2">
    <a class="btn btn-primary navlink" href="/Venue/Create">Add Venue</a>
</nav>

<div class="row">
    <div class="col-12">
        <form asp-controller="Team" asp-action="Index">
            <p>
                Search: <input type="text" name="Search" value="@ViewData["search"]" />
                <input type="submit" class="btn btn-primary" value="Search" />
            </p>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <table border="1">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Team Name</th>
                    <th>Country</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count() == 0)
                {
                    <tr class="text-center">
                        <td colspan="5">No Data Found</td>
                    </tr>
                }
                @{ int i = 1; }
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@i</td>
                        <td>@item.VenueDetail.Name</td>
                        <td>@item.VenueDetail.Country</td>
                        <td>
                            @Html.ActionLink("View", "Details", new { id = @item.Id }, new { @class = "btn btn-primary" })
                            @Html.ActionLink("Edit", "Edit", new { id = @item.VenueDetail.Id }, new { @class = "btn btn-warning" })
                            @Html.ActionLink("Delete", "DeleteConfirm", new { id = @item.Id }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>

                    i++;
                }
            </tbody>
        </table>
    </div>
</div>

<style>
    nav {
        padding-bottom: 1em;
    }

    table {
        width: 100%;
    }

    thead, tbody, tfoot, tr, td, th {
        border-width: 1px;
        padding: 0.25em;
    }
</style>

TMS/Views/Venue/List.cshtml
@model IEnumerable<TMS.Models.ViewModel.VenueDto>
@{
    ViewBag.Title = "List";
}

<h2>List</h2>
<a href="/Venue/New">New Venue</a>

@foreach (var Venue in Model)
{
    <h2>@Venue.Name</h2>
    <div>Base Price: @Venue.BasePrice</div>
    <div>Location: @Venue.Location</div>
    <div>Country: @Venue.Country</div>

    <div><a href="/Venue/Edit/@Venue.Id">Edit</a></div>
    <div><a href="/Venue/DeleteConfirm/@Venue.Id">Delete</a></div>


    // <a href="@Url.Action("ListMatchesForVenue", "Match", new { venueId = Venue.VenueId })">View Matches</a>
}